[package]
name = "vault-wrapper"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[[bin]]
name = "vault-debug"
path = "src/main.rs"

[dependencies]
vault = "10.1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libc = "0.2"

[profile.release]
lto = true